version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: >
    #   firebase emulators:exec "cd hostings/web && npm run dev -- --host 0.0.0.0" --import data --export-on-exit --project yosidev-staging
    working_dir: /app
    ports:
      - 4321:4321 # astro
    volumes:
      - ./:/app
    tty: true
