version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      yarn dev -- --host=0.0.0.0
    working_dir: /app
    ports:
      - 5173:5173 # vite
    volumes:
      - ./:/app
    tty: true
