version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      npm run dev -- -H 0.0.0.0
    working_dir: /app
    ports:
      - 3000:3000 # nextjs
    volumes:
      - ./:/app
    tty: true
